version: 2.1

orbs:
    python: circleci/python@1.2.1

jobs: 
    publish-docker:
        executor: python/default
        steps:
            - run: ECHO "TODO - deploy to docker hub"
            - run: ECHO "TODO - deploy to some server"

    build-docker:
        docker:
            - image: circleci/python:3.8.2
            - auth:
                username: $docker_username
                password: $docker_pw
        steps:
            - checkout
            - setup_remote_docker:
                version: 19.03.13
                docker_layer_caching: true
            - run: |
                TAG=0.1.$CIRCLE_BUILD_NUM
                docker build -t zmarkan/pypelines-minimal-app:$TAG .
                docker push zmarkan/pypelines-minimal-app:$TAG

            
    build-and-test:
        executor: python/default
        steps:
          - checkout
          - python/install-packages:
                pip-dependency-file: requirements.txt
                pkg-manager: pip
          - run: python app.test.py     
    
workflows:
  main:
    jobs:
      - build-and-test
      - build-docker
    

    

